### PR TITLE
[fix] Fixed mobile scaling issues with FileInfoDialog

### PR DESCRIPTION
**Pull request by NOCx420**
**Earlier:**
Hello, sorry for the earlier mess that was a pull request, I'm still getting the hang of things :)

**Mobile changes:**
I found the FileInformationDialog to be unusable on mobile, as the texts and buttons were all not scaling with the window size, and there was also the thumbnail or "preview" message on the side pushing everything even more off-screen. From now on the preview message should not show up when in mobile mode or any other kind of preview. The UI stuff like buttons and textboxes are now also correctly scaled and usable.

**Desktop changes:**
I also noticed that when in desktop mode, when listing a file's information, elements from the album section and under would go off screen and you could not navigate to them by scrolling. I've now made it so that the text and elements stay within the InformationDialog box and are able to be scrolled.

Video:
https://files.nocx420.xyz/dRCvTdlxtEV0.mp4

### CODE REVIEW

**Comment by Pitu** [comment]
Thank you for working on this, I'll check it out this week and get back to you!

**Comment by Pitu** [comment]
@NOCx420 sorry it took me so long to check this, I was on vacation.
For the portion of the changes that modify how it looks on mobile I see no issues, but I'm not sure about the second part. You mention that it's not possible to scroll down to the off-screen settings at the bottom of the dialog yet in the current version I'm able to do so as shown on the following video https://chibisafe.moe/GAH5oCll.mp4

Would you mind checking it out and if you experience the same, getting rid of those changes so that I can merge the mobile fix only?

Thanks!

**Comment by NOCx420** [comment]
@Pitu I have removed the changes you asked for, however on my side, scrolling doesn't work without them (https://files.nocx420.xyz/axQzcEDtjK6t.mp4). Might be a platform issue. I'm using linux and firefox, I'll try to look into what the problem might be.

**Comment by NOCx420** [comment]
Yep, it's definitely something with firefox. Scrolling works and elements don't overlap on chromium, but not on firefox. I'm still looking for what the issue could be, but honestly, I'm stuck for now.

**Review by Pitu — APPROVED** [review]

**Pull request merged**
