### PR TITLE
[WIP] various fixes and features

### PR DESCRIPTION
**Pull request by nopeless**

### CODE REVIEW

**Comment by nopeless** [comment]
I would like to hear your opinions on this before I proceed. lmk if you would rather do this on discord as well

**Comment by Pitu** [comment]
@nopeless thanks for reaching out, we're currently under a very heavy rewrite in the branch `feature/next` so I would recommend holding off on these.

**Comment by nopeless** [comment]
I just got here :agony:

Ok I'll hold on

**Comment by Pitu** [comment]
Feel free to open this again if you want to suggest changes.
You can open an issue first to discuss them or on our Discord server

**Pull request closed without merging**
