### PR TITLE
Feature/File-Expiry

### PR DESCRIPTION
**Pull request by test137E29B**
Adds automatic file deletion, and removal from albums after a configurable amount of days.

Notes:
- The cron job runs every 5 minutes, and gets all files older than the expiry boundary
- Database operations are batched
- Uses existing file deletion util
- Adds util for deleting array of files for more granular deletion logic in future (deletion of files with a query of any kind)
- Defaults to 30 days, but also defaulted to disabled to prevent old files with a new update just deleting for no reason

### CODE REVIEW

**Comment by Aareksio** [comment]
You shouldn't casually _include_ other, unrelated features in single PR. Nor modify package-lock.json for that matter.

In the code, you delete the file from DB twice by passing `true` as second parameter to `deleteFile`. If `deleteFile` were to fail, or process were terminated before `deleteAllFilesFromFileArray` finishes looping, you'd be left with files without entries in DB.

**Comment by test137E29B** [comment]
> You shouldn't casually _include_ other, unrelated features in single PR. Nor modify package-lock.json for that matter.
> 
> In the code, you delete the file from DB twice by passing `true` as second parameter to `deleteFile`. If `deleteFile` were to fail, or process were terminated before `deleteAllFilesFromFileArray` finishes looping, you'd be left with files without entries in DB.

Thanks for helping me understand some of the project better!

The lockfile is updated due to updating the target information for browserslist to be the latest.
Including the other change is because I didn't re-fork the PR, nor merge this all to it's own feature branch.

Will remove the API changes from this (as it's easier), and fix the deleteFile force

**Comment by test137E29B** [comment]
The following updates have been made:
- Removed api endpoint apikey changes - will submit another PR at a later date for these
- Fixed double db deletion. There is still rare cases in which it could be deleted from DB but not filesystem, but that should be incredibly rare. A design choice to make would be if it's better to instead drop records per file, rather than all at once at the expense of additional db operations for this to never occur

**Comment by Pitu** [comment]
Thank you for this PR. 
I'll be able to take a deeper look and try it myself sometime next week, so please hold until then.
From what I saw on the surface it looks good!

**Comment by Permanently** [comment]
I reckon there could be a bit more to this: e.g., deleting files that are older than 30 days **and** haven't received more than 10 visits in 7 days

**Comment by test137E29B** [comment]
> I reckon there could be a bit more to this: e.g., deleting files that are older than 30 days **and** haven't received more than 10 visits in 7 days

Would be nice i think to also have support for not deleting files with specific tags, at least in my usecase there's specific files I'd like to persist over these deletions

**Comment by test137E29B** [comment]
@Pitu maybe there's some update now on this PR? :P

**Comment by test137E29B** [comment]
Closing since this whole version is no longer active now - maybe will have to learn the new structure for v5 :))

**Comment by Pitu** [comment]
Thank you and sorry for not giving you an update.
The new version is way more extensible and this is in the roadmap!
That being said, we're trying to release a new feature weekly so this could be tackled in the following weeks

**Comment by test137E29B** [comment]
Thanks @Pitu ! No need for apologies, I was still using this branch with my changes anyway, so it didn't make much of a difference to me that it wasn't merged :))

I look forward to the future of the project!

**Pull request closed without merging**
