### PR TITLE
[Enhancement] Deployment documentation

### PR DESCRIPTION
**Pull request by Rake01**
This PR aims to help improve documentation for Chibisafe in regards to deployment. I have included a basic example using Docker and Caddy, but the goal is to have far more examples for users to choose from.
Note that the format which I have used should not be regarded as a strict requirement to follow. It can be as simple as a step-by-step document without any fluff.

### CODE REVIEW

**Comment by Aareksio** [comment]
Isn't it a bit complicated? Not sure what a beginner should do ("Quick setup" or "Basic setup").
Recommending HSTS to beginners is begging for trouble.

**Comment by Rake01** [comment]
Currently it's undergoing a bit of a structure change to simplify the steps a bit further. HSTS is recommended for making sure none of the resources are being fetched over HTTP. Thankfully, Caddy makes it relatively easy to change configs, so you can feel free to omit that step. I will be marking it as optional once I clean everything up.

**Comment by Aareksio** [comment]
HSTS, as it is currently recommended, makes the domain inaccessible over HTTP for 365 days, if the user decides to reuse it.
You can ensure no resources are accessible over HTTP using simple redirect - this is much more noob-friendly method.
In my eyes, it is very unlikely someone who needs to follow this guide is realistically going to benefit from HSTS.
At the same time, it is easy to imagine people asking why they can no longer access their domain after testing chibisafe.

**Comment by Rake01** [comment]
I'll keep the HSTS recommendation for now while marking it optional. In exchange, I have reduced the max age to 24hr.  I'll also leave a note that it is intended for permanent deployments.

**Pull request merged**
