### PR TITLE
[Fix] Frontend code changes and fixes

### PR DESCRIPTION
**Pull request by lakema17**
This PR intends to fix up several inconsistencies within the site. It also supersedes #543 and adds plenty of other fixes.
The affected pages/features are as follows:

- Front page
- Uploads page
- Albums page
- Tags page
- Snippets page
- Users page
- Sidebar navigation

Other pages may have been unintentionally changed due to modifications to underlying components, largely the Table component. I have checked to make sure that nothing is too out of place, and to my eye that seems to be the case.

If additional changes are needed to optimize or fix issues, please let me know.

### CODE REVIEW

**Comment by Pitu** [comment]
Thank you @lakema17, I only found one issue that needs to be solved before merging this:

https://chibisafe.moe/8djxjNxl.mp4

**Review by Pitu — CHANGES_REQUESTED** [review]
Thank you @lakema17, I found a few issues that needs to be solved before merging this:

- The modal contents get destroyed when resizing

https://github.com/chibisafe/chibisafe/assets/7425261/a1b6607a-7b4e-4953-859d-25830a08ce01

- The heading on the main page needs a padding right of 2rem
image

- The service name is not centered with the logo anymore
image

**Comment by lakema17** [comment]
Should be fixed now.

**Review by Pitu — APPROVED** [review]
Thank you!

**Pull request merged**
